import "./globals.css"
import { Inter, Playfair_Display } from "next/font/google"
import { Footer } from "@/components/layout/Footer";
import { Navbar } from "@/components/layout/Navbar";
import { BlogProvider } from "@/contexts/BlogContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-serif",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${playfair.variable} antialiased`}
      >
      <BlogProvider>
      <Navbar/>
      {children}
      <Footer/>
      </BlogProvider>

      </body>
    </html>
  );
}
